# User Roles
SUPER_ADMIN = "SUPER_ADMIN"
CLINIC_ADMIN = "CLINIC_ADMIN"
CLINIC_USER = "CLINIC_USER"

# Clinic Statuses
CLINIC_ACTIVE = "ACTIVE"
CLINIC_SUSPENDED = "SUSPENDED"
CLINIC_INACTIVE = "INACTIVE"

# User Statuses
USER_ACTIVE = "ACTIVE"
USER_INACTIVE = "INACTIVE"
USER_LOCKED = "LOCKED"
