"""Initial migration

Revision ID: initial_001
Revises: 
Create Date: 2026-06-09 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial_001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('centre_code', sa.String(length=20), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='clinic_status'), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_centre_code'), 'clinics', ['centre_code'], unique=True)
    op.create_index(op.f('ix_clinics_license_expiry'), 'clinics', ['license_expiry'], unique=False)
    op.create_index(op.f('ix_clinics_status'), 'clinics', ['status'], unique=False)
    
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('centre_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CLINIC_ADMIN', 'CLINIC_USER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', name='user_status'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['centre_code'], ['clinics.centre_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_centre_code'), 'users', ['centre_code'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('centre_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_centre_code'), 'audit_logs', ['centre_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_centre_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_centre_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clinics_status'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_license_expiry'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_centre_code'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
